SC2API: SC2API::UnitTestBase Class Reference
SC2API::UnitTestBase Class Reference abstract
#include <SC2APIUnitTestSystem.h>
Public Member Functions
virtual ~UnitTestBase ()
UnitTestBase ()=default
virtual const char * GetName () const =0
virtual float GetTimeOutDuration () const =0
virtual void SetupTest ()=0
virtual void RunTest ()=0
virtual void TeardownTest ()=0
void ReportError (std::string const &errorMessage)
template<typename A , typename B >
void TestEqual (const A &valueA, const B &valueB)
template<typename A , typename B >
void TestGreater (const A &valueA, const B &valueB)
Public Attributes
Signal< bool > Finished
Static Protected Member Functions
template<typename T >
static std::enable_if_t< std::is_arithmetic_v< T >, std::string > stringify (T t)
template<typename T >
static std::enable_if_t<!std::is_arithmetic_v< T >, std::string > stringify (T t)
template<>
static std::string stringify (char t)
Constructor & Destructor Documentation
virtual SC2API::UnitTestBase::~UnitTestBase () inline virtual
SC2API::UnitTestBase::UnitTestBase () default
Member Function Documentation
virtual const char* SC2API::UnitTestBase::GetName () const pure virtual
virtual float SC2API::UnitTestBase::GetTimeOutDuration () const pure virtual
void SC2API::UnitTestBase::ReportError (std::string const & errorMessage)
virtual void SC2API::UnitTestBase::RunTest () pure virtual
virtual void SC2API::UnitTestBase::SetupTest () pure virtual
template<typename T > static std::enable_if_t<std::is_arithmetic_v<T>, std::string> SC2API::UnitTestBase::stringify (T t) inline static protected
template<typename T > static std::enable_if_t<!std::is_arithmetic_v<T>, std::string> SC2API::UnitTestBase::stringify (T t) inline static protected
template<> static std::string SC2API::UnitTestBase::stringify (char t) inline static protected
References SC2API::GetTownCandidatePositionStandard(), SC2API::RegisterUnitTest(), SC2API_API, and SC2API::SignalRegisterUnitTests().
virtual void SC2API::UnitTestBase::TeardownTest () pure virtual
template<typename A , typename B > void SC2API::UnitTestBase::TestEqual (const A & valueA, const B & valueB) inline
template<typename A , typename B > void SC2API::UnitTestBase::TestGreater (const A & valueA, const B & valueB) inline
Member Data Documentation
Signal<bool > SC2API::UnitTestBase::Finished
The documentation for this class was generated from the following file:
SC2API/include/SC2APIUnitTestSystem.h