SC2API: SC2API Namespace Reference
SC2API Namespace Reference
Namespaces
Abils
Races
Units
Classes
struct Command
A command is the combination of an ability and an index for a command within that ability. Command indexes are 0 based.
class Creator
class Order
struct Point
struct Unit
SC2API Unit is an unreliable shell of the actual unit, representing the observable aspect of unit.
class UnitGroup
SC2API UnitGroup is a collection of units. Note the content is copied when assigned to another variable.
class UnitTestBase
Typedefs
using HandleId = unsigned int
Enumerations
enum UnitFilterFlag : int64_t {
UnitFilterFlag::Null = 0, UnitFilterFlag::Self = 1ULL << 0, UnitFilterFlag::Player = 1ULL << 1, UnitFilterFlag::Ally = 1ULL << 2,
UnitFilterFlag::Neutral = 1ULL << 3, UnitFilterFlag::Enemy = 1ULL << 4, UnitFilterFlag::Air = 1ULL << 5, UnitFilterFlag::Ground = 1ULL << 6,
UnitFilterFlag::Light = 1ULL << 7, UnitFilterFlag::Armored = 1ULL << 8, UnitFilterFlag::Biological = 1ULL << 9, UnitFilterFlag::Robotic = 1ULL << 10,
UnitFilterFlag::Mechanical = 1ULL << 11, UnitFilterFlag::Psionic = 1ULL << 12, UnitFilterFlag::Massive = 1ULL << 13, UnitFilterFlag::Structure = 1ULL << 14,
UnitFilterFlag::Hover = 1ULL << 15, UnitFilterFlag::Heroic = 1ULL << 16, UnitFilterFlag::MapObject = 1ULL << 17, UnitFilterFlag::Worker = 1ULL << 18,
UnitFilterFlag::RawResource = 1ULL << 19, UnitFilterFlag::HarvestableResource = 1ULL << 20, UnitFilterFlag::Missile = 1ULL << 21, UnitFilterFlag::Destructible = 1ULL << 22,
UnitFilterFlag::Item = 1ULL << 23, UnitFilterFlag::Uncommandable = 1ULL << 24, UnitFilterFlag::CanHaveEnergy = 1ULL << 25, UnitFilterFlag::CanHaveShields = 1ULL << 26,
UnitFilterFlag::PreventDefeat = 1ULL << 27, UnitFilterFlag::PreventReveal = 1ULL << 28, UnitFilterFlag::Buried = 1ULL << 29, UnitFilterFlag::Cloaked = 1ULL << 30,
UnitFilterFlag::Visible = 1ULL << 31, UnitFilterFlag::Stasis = 1ULL << 32, UnitFilterFlag::UnderConstruction = 1ULL << 33, UnitFilterFlag::Dead = 1ULL << 34,
UnitFilterFlag::Revivable = 1ULL << 35, UnitFilterFlag::Hidden = 1ULL << 36, UnitFilterFlag::Hallucination = 1ULL << 37, UnitFilterFlag::Invulnerable = 1ULL << 38,
UnitFilterFlag::HasEnergy = 1ULL << 39, UnitFilterFlag::HasShields = 1ULL << 40, UnitFilterFlag::Benign = 1ULL << 41, UnitFilterFlag::Passive = 1ULL << 42,
UnitFilterFlag::Detector = 1ULL << 43, UnitFilterFlag::Radar = 1ULL << 44, UnitFilterFlag::Stunned = 1ULL << 45, UnitFilterFlag::Summoned = 1ULL << 46,
UnitFilterFlag::Unstoppable = 1ULL << 47, UnitFilterFlag::Resistant = 1ULL << 49
}
Functions
SC2API_API void CheatSetGameSpeed (float factor)
Sets game speed to desired factor. Only valid when the game is single player. Supports maximum factor = 256.
SC2API_API Unit CheatCreateUnit (const std::string &inUnitType, Point inLocation)
Creates a unit at given point. Only valid when the game is single player.
SC2API_API void CheatRemoveUnit (const Unit &inUnit)
Removes a unit. Only valid when the game is single player.
SC2API_API void CheatSupply (int amount)
Adds given amount of supply limit. Only valid when the game is single player.
SC2API_API bool GameIsReplay ()
Determines whether the game is in replay mode.
SC2API_API bool GameIsSinglePlayer ()
Determines whether the game is single player (Only one client is running the game, so cheats and debugging are possible)
SC2API_API void OutputScreen (std::string Message)
Displays message only visible to local player in chat area of the screen.
SC2API_API Signal & SignalMatchStarted ()
Fires when a match or replay has started. Connect: void OnMatchStart();
SC2API_API Signal & SignalMatchEnded ()
Fires when a match or replay has ended. Connect: void OnMatchEnded();
SC2API_API Signal & SignalTimer (double timeOut, bool loop)
Sets a game timer to fire when time has passed. Connect: void OnTimer();
SC2API_API int PlayerLocal ()
Gets the local player's id.
SC2API_API std::string PlayerLocalRace ()
Returns the actual race of local player. The race is known even if random was chosen from the lobby.
SC2API_API std::string PlayerLobbyRace (int inPlayer)
Returns the race of the player chosen from lobby.
SC2API_API bool operator< (const Unit &lhs, const Unit &rhs)
SC2API_API bool operator> (const Unit &lhs, const Unit &rhs)
SC2API_API bool operator== (const Unit &lhs, const Unit &rhs)
SC2API_API bool operator!= (const Unit &lhs, const Unit &rhs)
SC2API_API Point GetTownCandidatePositionStandard ()
SC2API_API Signal & SignalRegisterUnitTests ()
SC2API_API void RegisterUnitTest (const char *name, Creator< UnitTestBase > unitTestCreator)
SC2API_API void LogLoader (std::string message)
Outputs a simple message line to loader window
Typedef Documentation
using SC2API::HandleId = typedef unsigned int
Enumeration Type Documentation
enum SC2API::UnitFilterFlag : int64_t strong
Enumerator
Null
Self
Player
Ally
Neutral
Enemy
Air
Ground
Light
Armored
Biological
Robotic
Mechanical
Psionic
Massive
Structure
Hover
Heroic
MapObject
Worker
RawResource
HarvestableResource
Missile
Destructible
Item
Uncommandable
CanHaveEnergy
CanHaveShields
PreventDefeat
PreventReveal
Buried
Cloaked
Visible
Stasis
UnderConstruction
Dead
Revivable
Hidden
Hallucination
Invulnerable
HasEnergy
HasShields
Benign
Passive
Detector
Radar
Stunned
Summoned
Unstoppable
Resistant
Function Documentation
SC2API_API Unit SC2API::CheatCreateUnit (const std::string & inUnitType, Point inLocation)
Creates a unit at given point. Only valid when the game is single player.
SC2API_API void SC2API::CheatRemoveUnit (const Unit & inUnit)
Removes a unit. Only valid when the game is single player.
SC2API_API void SC2API::CheatSetGameSpeed (float factor)
Sets game speed to desired factor. Only valid when the game is single player. Supports maximum factor = 256.
SC2API_API void SC2API::CheatSupply (int amount)
Adds given amount of supply limit. Only valid when the game is single player.
SC2API_API bool SC2API::GameIsReplay ()
Determines whether the game is in replay mode.
SC2API_API bool SC2API::GameIsSinglePlayer ()
Determines whether the game is single player (Only one client is running the game, so cheats and debugging are possible)
SC2API_API Point SC2API::GetTownCandidatePositionStandard ()
Referenced by SC2API::UnitTestBase::stringify().
SC2API_API void SC2API::LogLoader (std::string message)
Outputs a simple message line to loader window
SC2API_API bool SC2API::operator!= (const Unit & lhs, const Unit & rhs)
SC2API_API bool SC2API::operator< (const Unit & lhs, const Unit & rhs)
SC2API_API bool SC2API::operator== (const Unit & lhs, const Unit & rhs)
SC2API_API bool SC2API::operator> (const Unit & lhs, const Unit & rhs)
SC2API_API void SC2API::OutputScreen (std::string Message)
Displays message only visible to local player in chat area of the screen.
Parameters
Message String message to display
SC2API_API std::string SC2API::PlayerLobbyRace (int inPlayer)
Returns the race of the player chosen from lobby.
Returns
Terran, Zerg, Protoss or Random, see SC2API::Races
SC2API_API int SC2API::PlayerLocal ()
Gets the local player's id.
SC2API_API std::string SC2API::PlayerLocalRace ()
Returns the actual race of local player. The race is known even if random was chosen from the lobby.
Returns
Terran, Zerg or Protoss, see SC2API::Races
SC2API_API void SC2API::RegisterUnitTest (const char * name, Creator< UnitTestBase > unitTestCreator)
Referenced by SC2API::UnitTestBase::stringify().
SC2API_API Signal& SC2API::SignalMatchEnded ()
Fires when a match or replay has ended. Connect: void OnMatchEnded();
Returns
Signal for binding
SC2API_API Signal& SC2API::SignalMatchStarted ()
Fires when a match or replay has started. Connect: void OnMatchStart();
Returns
Signal for binding
SC2API_API Signal& SC2API::SignalRegisterUnitTests ()
Referenced by SC2API::UnitTestBase::stringify().
SC2API_API Signal& SC2API::SignalTimer (double timeOut, bool loop)
Sets a game timer to fire when time has passed. Connect: void OnTimer();